### ISSUE TITLE
ODX - Possible block time adjustment

### ISSUE THREAD

**Issue by aubergemediale** [obsidianproject/Obsidian-StratisNode#2]
It is being considered to increase the time interval between blocks on the ODX network, to reduce fullnode data/bandwidth for mobile full nodes. Decision and implementation.

E.g. to every 2.5-5 minutes instead of every 1 minute.

**Comment by dangershony** [comment]
This is done but its part of a bigger task where we also need to change the following

- [ ] maxreorg - I propose a value of 500/4=125 
- [ ] coinbase maturity - 50 (no need to change that IMO)
- [ ]  coinstake age - 500/4=125 (this must be the same or higher then maxreorg for security reasons)

Previously this values where 500 per min which is 8.3 hours we maintain that roughly that same number

**Comment by dangershony** [comment]
#### Block reward for POW era

I propose a POW era of 5000 blocks (roughly two weeks) with a minimal reward (perhaps 5 ODX) POW is only there to bootstrap POS but the airdrop will already distribute sufficient coins to have a good staking base.

#### Block reward for POS 

As described here #1 block rewards will increase to compensate on the airdrop cut for the first 2 years rewards will be at 150 ODX per block (every 4 min) at block 240,000 (roughly two years) this will be cut back to be 20 ODX


The total premine is still not clear finalized.

**Comment by dangershony** [comment]
This is now done
