### ISSUE TITLE
ODX - Ensure ODX is 'SegWit-only'

### ISSUE THREAD

**Issue by aubergemediale** [obsidianproject/Obsidian-StratisNode#4]
- Imo, 'SegWit only' is a good selling point, and BTC will envy us for that.
- Even though NBitcoin can obviously handle both, 'SegWit-only' reduces the amount of code required dramatically.
- Full support of SegWit _and_ legacy results in a lot of very complex code, especially because the types can be mixed/embedded with each other.
- SegWit is better
- ...

This can largely implemented with consensus rules/not specifying Base58 types,  so that no refactoring is necessary.

**Comment by dangershony** [comment]
I think we can close this one right?

**Comment by aubergemediale** [comment]
yes, cool we did it! :-)
